# Generated by Django 4.0 on 2021-12-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('kakao_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(default='undefined', max_length=10)),
                ('point', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
